services:
  sales-tracker:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - db-data:/app/data
    environment:
      - DB_PATH=/app/data/sales.db
    restart: unless-stopped


volumes:
  db-data:
